NUMPY ASSIGNMENT - 28-01-2024

In [29]:
print("A Python library is a collection of pre-written and reusable code that can be imported and used in Python programs. These libraries consist of modules, which are sets of functions and classes that perform specific tasks. Libraries help simplify the development process by providing pre-built functionality, allowing developers to leverage existing code rather than starting from scratch.")

A Python library is a collection of pre-written and reusable code that can be imported and used in Python programs. These libraries consist of modules, which are sets of functions and classes that perform specific tasks. Libraries help simplify the development process by providing pre-built functionality, allowing developers to leverage existing code rather than starting from scratch.


In [30]:
print('''Data Type:

In a NumPy array, all elements must have the same data type.
Lists can contain elements of different data types.
      
Memory Efficiency:

NumPy arrays are more memory efficient compared to lists, especially for large datasets, because they store data in a contiguous block of memory.
Lists, being more flexible, may result in higher memory usage due to the overhead of storing type information for each element.''')

Data Type:

In a NumPy array, all elements must have the same data type.
Lists can contain elements of different data types.
      
Memory Efficiency:

NumPy arrays are more memory efficient compared to lists, especially for large datasets, because they store data in a contiguous block of memory.
Lists, being more flexible, may result in higher memory usage due to the overhead of storing type information for each element.


In [1]:
import numpy as np
m=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("The shape of the matrix is ",np.shape(m))
print("The size of the matrix is ",np.size(m))
print("The dimensions of the matrix is ",np.ndim(m))

The shape of the matrix is  (3, 4)
The size of the matrix is  12
The dimensions of the matrix is  2


In [10]:
m=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(m[0, :])

[1 2 3 4]


In [9]:
m=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(m[2, 3])

12


In [12]:
m=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(m[:, 1::2])

[[ 2  4]
 [ 6  8]
 [10 12]]


In [13]:
n=np.random.rand(3,3)
print(n)

[[0.65789488 0.71620994 0.59514406]
 [0.2830807  0.94049151 0.23992502]
 [0.58259723 0.17106604 0.27161979]]


In [3]:
print("np.random.rand generates random values from a uniform distribution between 0 and 1, while np.random.randn generates random values from a standard normal distribution with a mean of 0 and a standard deviation of 1.")

np.random.rand generates random values from a uniform distribution between 0 and 1, while np.random.randn generates random values from a standard normal distribution with a mean of 0 and a standard deviation of 1.


In [5]:
import numpy as np
arr = np.array([[1, 2, 3, 4],
                          [5, 6, 7, 8],
                          [9, 10, 11, 12]])
increased_dimension = arr[:, :, np.newaxis]
print(increased_dimension)

[[[ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]
  [12]]]


In [6]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
tra = np.transpose(arr)
print(tra)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [22]:
A = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
B = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
# index wise multiplication.
mul = [[i*j for i,j in zip(a,b)] for a,b in zip(A,B)]
print(mul)
# multiplication matrix
mul1 = np.dot(A, np.transpose(B))
print(mul1)
# Add the both matrix
add = [[i+j for i,j in zip(a,b)] for a,b in zip(A,B)]
print(add)
# Subtract the both matrix
sub = [[i-j for i,j in zip(a,b)] for a,b in zip(A,B)]
print(sub)
# Divide the A from B
div = [[b / a if a != 0 else 0 for a, b in zip(row_a, row_b)] for row_a, row_b in zip(A, B)]
print(div)

[[1, 4, 9, 16], [25, 36, 49, 64], [81, 100, 121, 144]]
[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]
[[2, 4, 6, 8], [10, 12, 14, 16], [18, 20, 22, 24]]
[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]
[[1.0, 1.0, 1.0, 1.0], [1.0, 1.0, 1.0, 1.0], [1.0, 1.0, 1.0, 1.0]]


In [25]:
import numpy as np
arr = np.array([1, 2, 3, 4], dtype=np.int32)
swap_arr = arr.byteswap()
print("Swapped Array:", swap_arr)

Swapped Array: [16777216 33554432 50331648 67108864]


In [26]:
print("The np.linalg.inv function in Python, provided by the NumPy library, is used to compute the (multiplicative) inverse of a matrix. In linear algebra, the inverse of a matrix is a matrix that, when multiplied with the original matrix, results in the identity matrix.")

The np.linalg.inv function in Python, provided by the NumPy library, is used to compute the (multiplicative) inverse of a matrix. In linear algebra, the inverse of a matrix is a matrix that, when multiplied with the original matrix, results in the identity matrix.


In [27]:
print("The np.reshape function in NumPy is used to change the shape of an array. It allows you to rearrange the elements of an array into a new shape without changing their values.")

The np.reshape function in NumPy is used to change the shape of an array. It allows you to rearrange the elements of an array into a new shape without changing their values.


In [28]:
print("NumPy broadcasting refers to the ability of arrays with different shapes to be combined or operated upon element-wise. NumPy automatically broadcasts arrays when performing operations, allowing you to perform calculations on arrays of different shapes and sizes without explicitly reshaping them.")

NumPy broadcasting refers to the ability of arrays with different shapes to be combined or operated upon element-wise. NumPy automatically broadcasts arrays when performing operations, allowing you to perform calculations on arrays of different shapes and sizes without explicitly reshaping them.


THANK YOU FOR GIVING THIS ASSIGNMENT